(defpackage :cl-cycle
  (:use :cl)
  (:export
   :KAPREKAR-CONSTANT
   :RHYTHMIC-SIEVE
   :PEA-PATTERN
   :SYMMETRIC-GROUP
   :SYMMETRIC-PERMUTATION
   :KREUZSPIEL-PERMUTATION
   :CIRCULAR-PERMUTATION
   :LORENZ-DISCRETISATION
   :COLLATZ-CONJECTURE
   :INTERLACE-CYCLE
   :EUCLIDEAN-RHYTHM
   :CAMPANOLOGY-PERMUTATION
   :DISCRETE-LOGARITHM
   
   :10->N
   :N->10  
   
   :MK-INTEGER-LST
   :FILL-DIGIT-LST

   :*cycle-default-value*
   )
  )
